### ISSUE TITLE
580 not imported

### ISSUE THREAD

**Issue by e2d2** [cul-it/cornell_marc_importer#17]
580 field (notes) not imported:
ex: https://newcatalog.library.cornell.edu/catalog/9667755/librarian_view 

Realize it's not in the mapping template. Will need to figure out where it goes.

**Comment by e2d2** [comment]
Marcie and I would like to see a report of all the content in the 580. It's a linking field, but we're not sure how it's been used over all.

**Comment by starsplatter** [comment]
We're going to just let the 580s hang in Voyager and not manage or create them in ASpace.
